test:
  weight: 1
asteroid:
  nickel:
    name: "Nickel Ore"
    type: "Ore"
    weight: 1
  iron:
    name: "Iron Ore"
    type: "Ore"
    weight: 1
  cobalt:
    name: "Cobalt Ore"
    type: "Ore"
    weight: 1