test:
  weight: 1
  
# Asteroids
asteroid:
  nickel:
    name: "Nickel Ore"
    type: "Ore"
    weight: 1
  iron:
    name: "Iron Ore"
    type: "Ore"
    weight: 1
  cobalt:
    name: "Cobalt Ore"
    type: "Ore"
    weight: 1

# Equipment
equipment:

  # Weapons
  weapons:
    laser_gatling:
      name: "Laser Gatling"
      type: "Weapon"
      weight: 4
      damage_amplifier: 1.3
      slot_type: "main"
    try_pyon_laser:
      name: "Try Pyon Laser"
      type: "Weapon"
      weight: 5
      damage_amplifier: 1.6
      slot_type: "main"
      
  # Hulls
  hulls:
    light_hull:
      name: "Light Hull"
      type: "Hull"
      weight: 2
      align_amplifier: 0.8
      slot_type: "utility"
      
  # Scanner
  scanner:
    small_scanner:
      name: "Small Scanner"
      type: "Scanner"
      weight: 2
      target_amplifier: 0.8
      slot_type: "utility"
      
  # Miner
  miner:
    basic_miner:
      name: "Basic Mining Laser"
      type: "Mining Laser"
      weight: 2
      mining_amount: 1
      slot_type: "main"
    advanced_miner:
      name: "Adv. Mining Laser"
      type: "Mining Laser"
      weight: 2
      mining_amount: 2
      slot_type: "main"
      
  # Defense
  defense:
    ion_shield:
      name: "Ion Shield"
      type: "Defense"
      weight: 4
      defense_amplifier: 1.1
      slot_type: "main"
    try_pyon_shield:
      name: "Try Pyon Shield"
      type: "Defense"
      weight: 5
      defense_amplifier: 1.2
      slot_type: "main"
      
  storage:
    small_black_hole:
      name: "Small Black Hole"
      type: "Storage"
      weight: 5
      storage_amplifier: 1.2
      slot_type: "utility"
  