test:
  weight: 1
  
# Asteroids
asteroid:
  nickel:
    name: "Nickel Ore"
    type: "Ore"
    weight: 1
  iron:
    name: "Iron Ore"
    type: "Ore"
    weight: 1
  cobalt:
    name: "Cobalt Ore"
    type: "Ore"
    weight: 1
  septarium:
    name: "Septarium"
    type: "Ore"
    weight: 0

# Equipment
equipment:

  # Weapons
  weapons:
    laser_gatling:
      name: "Laser Gatling"
      type: "Weapon"
      weight: 4
      damage: 5
      slot_type: "main"
      septarium_usage: 2
      crafting: {"asteroid.nickel": 15, "asteroid.cobalt": 20, "materials.laser_diodes": 5}
      crafting_duration: 200
    try_pyon_laser:
      name: "Try Pyon Laser"
      type: "Weapon"
      weight: 5
      damage: 10
      slot_type: "main"
      septarium_usage: 10
      crafting: {"asteroid.nickel": 30, "asteroid.cobalt": 40, "materials.laser_diodes": 15}
      crafting_duration: 200
      
  # Hulls
  hulls:
    light_hull:
      name: "Light Hull"
      type: "Hull"
      weight: 2
      align_amplifier: 0.8
      slot_type: "utility"
      crafting: {"asteroid.nickel": 15, "asteroid.cobalt": 20, "materials.metal_plates": 15}
      crafting_duration: 200
      
  # Scanner
  scanner:
    small_scanner:
      name: "Small Scanner"
      type: "Scanner"
      weight: 2
      target_amplifier: 0.8
      slot_type: "utility"
      crafting: {"asteroid.iron": 30, "asteroid.cobalt": 10, "materials.sensor_electronics": 30}
      crafting_duration: 200
      
  # Warp Disruptors
  warp_disruptors:
    basic_warp_disruptor:
      name: "Basic Warp Disruptor"
      type: "Warp Disruptor"
      weight: 2
      disrupt_strength: 1
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.iron": 30, "materials.sensor_electronics": 15}
      crafting_duration: 200
  
  # Warp Core Stabilizers   
  warp_core_stabilizers:
    warp_core_stabilizer:
      name: "Warp Core Stabilizer"
      type: "Warp Core Stabilizer"
      weight: 2
      disrupt_immunity: 1
      slot_type: "utility"
      crafting: {"asteroid.nickel": 30, "materials.fusion_electronics": 15}
      crafting_duration: 200
      
  # Miner
  miner:
    basic_miner:
      name: "Basic Mining Laser"
      type: "Mining Laser"
      weight: 2
      mining_amount: 1
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.nickel": 15, "asteroid.iron": 15, "asteroid.septarium": 15}
      crafting_duration: 200
    advanced_miner:
      name: "Adv. Mining Laser"
      type: "Mining Laser"
      weight: 2
      mining_amount: 2
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.nickel": 30, "asteroid.iron": 30, "asteroid.septarium": 30}
      crafting_duration: 200
      
  # Repair Bots
  repair_bots:
    simple_repair_bot:
      name: "Basic Repair Bot"
      type: "Repair Bot"
      weight: 3
      repair_amount: 3
      slot_type: "main"
      septarium_usage: 2
      crafting: {"asteroid.cobalt": 15, "asteroid.iron": 15, "materials.ai_components": 10}
      crafting_duration: 200
      
  # Defense
  defense:
    ion_shield:
      name: "Ion Shield"
      type: "Defense"
      weight: 4
      defense_amplifier: 1.1
      slot_type: "utility"
      crafting: {"asteroid.cobalt": 15, "asteroid.nickel": 15, "materials.fusion_electronics": 6}
      crafting_duration: 200
    try_pyon_shield:
      name: "Try Pyon Shield"
      type: "Defense"
      weight: 5
      defense_amplifier: 1.2
      slot_type: "utility"
      crafting: {"asteroid.cobalt": 45, "asteroid.nickel": 25, "materials.fusion_electronics": 22}
      crafting_duration: 200
      
  storage:
    small_black_hole:
      name: "Small Black Hole"
      type: "Storage"
      weight: 5
      storage_amplifier: 1.2
      slot_type: "utility"
      crafting: {"asteroid.iron": 10, "asteroid.nickel": 25, "materials.antimatter": 4}
      crafting_duration: 200
      
# Materials for Crafting
materials:
  sensor_electronics:
    name: "Sensor Electronics"
    type: "Material"
    weight: 1
  
  antimatter:
    name: "Antimatter"
    type: "Material"
    weight: 1
    
  fusion_electronics:
    name: "Fusion Electronics"
    type: "Material"
    weight: 1
    
  ai_components:
    name: "AI Components"
    type: "Material"
    weight: 1
    
  metal_plates:
    name: "Metal Plates"
    type: "Material"
    weight: 1
    
  laser_diodes:
    name: "Laser Diodes"
    type: "Material"
    weight: 1