test:
  weight: 1
  
# Asteroids
asteroid:
  nickel_ore:
    name: "Nickel Ore"
    type: "Ore"
    weight: 1
    price: 9
  iron_ore:
    name: "Iron Ore"
    type: "Ore"
    weight: 1
    price: 9
  cobalt_ore:
    name: "Cobalt Ore"
    type: "Ore"
    weight: 1
    price: 9
  septarium_ore:
    name: "Septarium"
    type: "Ore"
    weight: 0
    price: 4
  titanium_ore:
    name: "Titanium"
    type: "Ore"
    weight: 1
    price: 20

# Equipment
equipment:

  # Weapons
  weapons:
    laser_gatling:
      name: "Gatling Laser"
      type: "Weapon"
      weight: 4
      damage: 5
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.nickel_ore": 5, "asteroid.cobalt_ore": 10, "materials.laser_diodes": 1}
      crafting_duration: 10
      price: 120
    try_pyon_laser:
      name: "Try Pyon Laser"
      type: "Weapon"
      weight: 5
      damage: 10
      slot_type: "main"
      septarium_usage: 2
      crafting: {"asteroid.nickel_ore": 30, "asteroid.cobalt_ore": 40, "materials.laser_diodes": 15}
      crafting_duration: 40
      price: 1200
    military_laser:
      name: "Military Laser"
      type: "Weapon"
      weight: 10
      damage: 20
      slot_type: "main"
      septarium_usage: 5
      crafting: {"asteroid.nickel_ore": 60, "asteroid.cobalt_ore": 80, "materials.laser_diodes": 30, "asteroid.titanium_ore": 10}
      crafting_duration: 120
      price: 2550
      
  # Hulls
  hulls:
    light_hull:
      name: "Light Hull"
      type: "Hull"
      weight: 2
      align_amplifier: 0.8
      slot_type: "utility"
      crafting: {"asteroid.nickel_ore": 15, "asteroid.cobalt_ore": 20, "materials.metal_plates": 15}
      crafting_duration: 25
      price: 750
    ultralight_hull:
      name: "Ultralight Hull"
      type: "Hull"
      weight: 1
      align_amplifier: 0.7
      slot_type: "utility"
      crafting: {"asteroid.nickel_ore": 30, "asteroid.cobalt_ore": 30, "materials.metal_plates": 30}
      crafting_duration: 40
      price: 1350
      
  # Sensors
  sensors:
    small_sensor:
      name: "Small Sensor"
      type: "Sensor"
      weight: 2
      target_amplifier: 0.8
      slot_type: "utility"
      crafting: {"asteroid.iron_ore": 30, "asteroid.cobalt_ore": 10, "materials.sensor_electronics": 30}
      crafting_duration: 40
      price: 1200
    try_pyon_sensor:
      name: "Try Pyon Sensor"
      type: "Sensor"
      weight: 2
      target_amplifier: 0.7
      slot_type: "utility"
      crafting: {"asteroid.iron_ore": 60, "asteroid.cobalt_ore": 15, "materials.sensor_electronics": 50}
      crafting_duration: 70
      price: 2100
      
  scanner:
    basic_scanner:
      name: "Basic Scanner"
      type: "Scanner"
      weight: 2
      scanner_range: 1
      septarium_usage: 0
      slot_type: "main"
      crafting: {"asteroid.iron_ore": 30, "asteroid.cobalt_ore": 10, "materials.sensor_electronics": 30}
      crafting_duration: 50
      price: 1200
    advanced_scanner:
      name: "Advanced Scanner"
      type: "Scanner"
      weight: 2
      scanner_range: 2
      septarium_usage: 0
      slot_type: "main"
      crafting: {"asteroid.iron_ore": 60, "asteroid.cobalt_ore": 25, "materials.sensor_electronics": 40}
      crafting_duration: 75
      price: 1800
    military_scanner:
      name: "Military Scanner"
      type: "Scanner"
      weight: 4
      scanner_range: 4
      septarium_usage: 0
      slot_type: "main"
      crafting: {"asteroid.iron_ore": 100, "asteroid.cobalt_ore": 50, "materials.sensor_electronics": 65, "asteroid.titanium_ore": 10}
      crafting_duration: 150
      price: 3300
      
  # Warp Disruptors
  warp_disruptors:
    basic_warp_disruptor:
      name: "Basic Warp Disruptor"
      type: "Warp Disruptor"
      weight: 2
      disrupt_strength: 1
      slot_type: "main"
      septarium_usage: 1
      crafting: {"asteroid.iron_ore": 30, "materials.sensor_electronics": 15}
      crafting_duration: 25
      price: 750
    try_pyon_warp_disruptor:
      name: "Try Pyon Warp Disruptor"
      type: "Warp Disruptor"
      weight: 4
      disrupt_strength: 2
      slot_type: "main"
      septarium_usage: 2
      crafting: {"asteroid.iron_ore": 60, "materials.sensor_electronics": 30}
      crafting_duration: 45
      price: 1350
    military_warp_disruptor:
      name: "Military Warp Disruptor"
      type: "Warp Disruptor"
      weight: 10
      disrupt_strength: 3
      slot_type: "main"
      septarium_usage: 5
      crafting: {"asteroid.iron_ore": 100, "materials.sensor_electronics": 30, "materials.fusion_electronics": 30, "asteroid.titanium_ore": 10}
      crafting_duration: 100
      price: 2700
  
  # Warp Core Stabilizers   
  warp_core_stabilizers:
    basic_warp_core_stabilizer:
      name: "Basic Warp Core Stabilizer"
      type: "Warp Core Stabilizer"
      weight: 2
      disrupt_immunity: 1
      slot_type: "utility"
      crafting: {"asteroid.nickel_ore": 30, "materials.fusion_electronics": 15}
      crafting_duration: 20
      price: 750
    try_pyon_warp_core_stabilizer:
      name: "Try Pyon Warp Core Stabilizer"
      type: "Warp Core Stabilizer"
      weight: 4
      disrupt_immunity: 2
      slot_type: "utility"
      crafting: {"asteroid.nickel_ore": 60, "materials.fusion_electronics": 45}
      crafting_duration: 60
      price: 1800
    military_warp_core_stabilizer:
      name: "Military Warp Core Stabilizer"
      type: "Warp Core Stabilizer"
      weight: 10
      disrupt_immunity: 3
      slot_type: "utility"
      crafting: {"asteroid.nickel_ore": 100, "materials.fusion_electronics": 60, "asteroid.titanium_ore": 10}
      crafting_duration: 80
      price: 2700
      
  # Miner
  miner:
    basic_miner:
      name: "Basic Mining Laser"
      type: "Mining Laser"
      weight: 2
      mining_amount: 1
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.nickel_ore": 5, "asteroid.iron_ore": 10, "asteroid.septarium": 5}
      crafting_duration: 5
      price: 105
    advanced_miner:
      name: "Adv. Mining Laser"
      type: "Mining Laser"
      weight: 2
      mining_amount: 2
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.nickel_ore": 30, "asteroid.iron_ore": 30, "asteroid.septarium": 30}
      crafting_duration: 20
      price: 450
    core_miner:
      name: "Core Mining Laser"
      type: "Mining Laser"
      weight: 5
      mining_amount: 3
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.nickel_ore": 100, "asteroid.iron_ore": 100, "asteroid.titanium_ore": 50}
      crafting_duration: 75
      price: 2100
      
  # Repair Bots
  repair_bots:
    simple_repair_bot:
      name: "Basic Repair Bot"
      type: "Repair Bot"
      weight: 3
      repair_amount: 3
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.cobalt_ore": 15, "asteroid.iron_ore": 15, "materials.ai_components": 10}
      crafting_duration: 20
      price: 540
    advanced_repair_bot:
      name: "Advanced Repair Bot"
      type: "Repair Bot"
      weight: 5
      repair_amount: 5
      slot_type: "main"
      septarium_usage: 2
      crafting: {"asteroid.cobalt_ore": 30, "asteroid.iron_ore": 45, "materials.ai_components": 20}
      crafting_duration: 35
      price: 1050
    colton_repair_bot:
      name: "Colton Repair Bot"
      type: "Repair Bot"
      weight: 10
      repair_amount: 8
      slot_type: "main"
      septarium_usage: 5
      crafting: {"asteroid.cobalt_ore": 75, "asteroid.iron_ore": 50, "materials.ai_components": 30, "asteroid.titanium_ore": 10}
      crafting_duration: 50
      price: 1650
  
  # Remote Repair Beam
  remote_repair:
    simple_repair_beam:
      name: "Simple Repair Beam"
      type: "Repair Beam"
      weight: 3
      repair_amount: 3
      slot_type: "main"
      septarium_usage: 0
      crafting: {"asteroid.cobalt_ore": 15, "asteroid.iron_ore": 15, "materials.ai_components": 10}
      crafting_duration: 20
      price: 540
    advanced_repair_beam:
      name: "Advanced Repair Beam"
      type: "Repair Beam"
      weight: 5
      repair_amount: 5
      slot_type: "main"
      septarium_usage: 2
      crafting: {"asteroid.cobalt_ore": 30, "asteroid.iron_ore": 45, "materials.ai_components": 20}
      crafting_duration: 35
      price: 1050
    colton_repair_beam:
      name: "Colton Repair Beam"
      type: "Repair Beam"
      weight: 10
      repair_amount: 8
      slot_type: "main"
      septarium_usage: 5
      crafting: {"asteroid.cobalt_ore": 75, "asteroid.iron_ore": 50, "materials.ai_components": 30, "asteroid.titanium_ore": 10}
      crafting_duration: 50
      price: 1650
      
  # Defense
  defense:
    ion_shield:
      name: "Ion Shield"
      type: "Defense"
      weight: 4
      defense_amplifier: 1.05
      slot_type: "utility"
      crafting: {"asteroid.cobalt_ore": 15, "asteroid.nickel_ore": 15, "materials.fusion_electronics": 6}
      crafting_duration: 10
      price: 300
    try_pyon_shield:
      name: "Try Pyon Shield"
      type: "Defense"
      weight: 5
      defense_amplifier: 1.1
      slot_type: "utility"
      crafting: {"asteroid.cobalt_ore": 45, "asteroid.nickel_ore": 25, "materials.fusion_electronics": 22}
      crafting_duration: 40
      price: 1200
      
  storage:
    small_black_hole:
      name: "Small Black Hole"
      type: "Storage"
      weight: 5
      storage_amplifier: 1.2
      slot_type: "utility"
      crafting: {"asteroid.iron_ore": 10, "asteroid.nickel_ore": 25, "materials.antimatter": 4}
      crafting_duration: 10
      price: 450
    medium_black_hole:
      name: "Medium Black Hole"
      type: "Storage"
      weight: 10
      storage_amplifier: 1.4
      slot_type: "utility"
      crafting: {"asteroid.iron_ore": 20, "asteroid.nickel_ore": 50, "materials.antimatter": 10}
      crafting_duration: 30
      price: 825
    large_black_hole:
      name: "Large Black Hole"
      type: "Storage"
      weight: 20
      storage_amplifier: 1.6
      slot_type: "utility"
      crafting: {"asteroid.iron_ore": 20, "asteroid.nickel_ore": 50, "materials.antimatter": 50, "asteroid.titanium_ore": 10}
      crafting_duration: 70
      price: 2175
      
# Materials for Crafting
materials:
  sensor_electronics:
    name: "Sensor Electronics"
    type: "Material"
    weight: 1
    price: 30
  
  antimatter:
    name: "Antimatter"
    type: "Material"
    weight: 1
    price: 30
    
  fusion_electronics:
    name: "Fusion Electronics"
    type: "Material"
    weight: 1
    price: 30
    
  ai_components:
    name: "AI Components"
    type: "Material"
    weight: 1
    price: 30
    
  metal_plates:
    name: "Metal Plates"
    type: "Material"
    weight: 1
    price: 30
    
  laser_diodes:
    name: "Laser Diodes"
    type: "Material"
    weight: 1
    price: 30