Nano:
  image: nano.png
  thruster-image: nano-thrusters.png
  storage: 10
  hp: 150
  defense: 10
  price: 0
  main_equipment_slots: 2
  utility_equipment_slots: 0
  align_time: 5
  target_time: 5
  crafting: {"asteroid.nickel": 5, "asteroid.cobalt": 10, "materials.laser_diodes": 1}
  crafting_duration: 10
  
Cerux:
  image: cerux.png
  thruster-image: cerux-thrusters.png
  storage: 40
  hp: 750
  defense: 60
  price: 12000
  main_equipment_slots: 4
  utility_equipment_slots: 3
  align_time: 10
  target_time: 10
  crafting: {"asteroid.nickel": 30, "asteroid.cobalt": 40, "materials.laser_diodes": 15}
  crafting_duration: 200

Valadria:
  image: valadria.png
  thruster-image: valadria-thrusters.png
  storage: 35
  hp: 600
  defense: 30
  price: 10000
  main_equipment_slots: 4
  utility_equipment_slots: 2
  align_time: 10
  target_time: 7
  crafting: {"asteroid.nickel": 30, "asteroid.cobalt": 40, "materials.laser_diodes": 15}
  crafting_duration: 200
  
Crasher:
  image: crasher.png
  thruster-image: crasher-thrusters.png
  storage: 15
  hp: 300
  defense: 10
  price: 8000
  main_equipment_slots: 3
  utility_equipment_slots: 1
  align_time: 3
  target_time: 3
  crafting: {"asteroid.nickel": 30, "asteroid.cobalt": 40, "materials.laser_diodes": 15}
  crafting_duration: 200
  
Chronos:
  image: chronos.png
  thruster-image: chronos-thrusters.png
  storage: 80
  hp: 225
  defense: 60
  price: 5000
  main_equipment_slots: 1
  utility_equipment_slots: 4
  align_time: 15
  target_time: 15
  crafting: {"asteroid.nickel": 30, "asteroid.cobalt": 40, "materials.laser_diodes": 15}
  crafting_duration: 200