# Ship Classes
# Multipurpose, Combat, Freighter, Hunter

Nano:
  image: nano.png
  thruster-image: nano-thrusters.png
  storage: 10
  hp: 150
  defense: 10
  price: 0
  main_equipment_slots: 2
  utility_equipment_slots: 0
  align_time: 5
  target_time: 5
  crafting: {"asteroid.nickel_ore": 5, "asteroid.cobalt_ore": 10, "materials.laser_diodes": 1}
  crafting_duration: 5
  type: "Multipurpose"
  
Cerux:
  image: cerux.png
  thruster-image: cerux-thrusters.png
  storage: 45
  hp: 750
  defense: 30
  price: 19500
  main_equipment_slots: 2
  utility_equipment_slots: 2
  align_time: 10
  target_time: 10
  crafting: {"asteroid.nickel_ore": 275, "asteroid.cobalt_ore": 400, "materials.laser_diodes": 450, "asteroid.titanium_ore": 100}
  crafting_duration: 700
  type: "Combat"

Valadria:
  image: valadria.png
  thruster-image: valadria-thrusters.png
  storage: 35
  hp: 600
  defense: 25
  price: 13500
  main_equipment_slots: 2
  utility_equipment_slots: 1
  align_time: 10
  target_time: 10
  crafting: {"asteroid.iron_ore": 190, "asteroid.cobalt_ore": 300, "materials.metal_plates": 250, "asteroid.titanium_ore": 100}
  crafting_duration: 500
  type: "Combat"
  
Crasher:
  image: crasher.png
  thruster-image: crasher-thrusters.png
  storage: 10
  hp: 300
  defense: 10
  price: 9000
  main_equipment_slots: 3
  utility_equipment_slots: 1
  align_time: 3
  target_time: 3
  crafting: {"asteroid.nickel_ore": 140, "asteroid.cobalt_ore": 200, "materials.antimatter": 175, "asteroid.titanium_ore": 50}
  crafting_duration: 350
  type: "Hunter"
  
Chronos:
  image: chronos.png
  thruster-image: chronos-thrusters.png
  storage: 80
  hp: 225
  defense: 25
  price: 13500
  main_equipment_slots: 1
  utility_equipment_slots: 3
  align_time: 15
  target_time: 15
  crafting: {"asteroid.nickel_ore": 275, "asteroid.iron_ore": 400, "materials.laser_diodes": 250, "asteroid.titanium_ore": 100}
  crafting_duration: 500
  type: "Freighter"
  
Revenant:
  image: revenant.png
  thruster-image: revenant-thrusters.png
  storage: 40
  hp: 200
  defense: 15
  price: 7500
  main_equipment_slots: 2
  utility_equipment_slots: 2
  align_time: 8
  target_time: 5
  crafting: {"asteroid.iron_ore": 140, "asteroid.cobalt_ore": 400, "materials.fusion_electronics": 75, "materials.antimatter": 25}
  crafting_duration: 300
  type: "Multipurpose"
  
Atlas:
  image: atlas.png
  thruster-image: atlas-thrusters.png
  storage: 150
  hp: 1500
  defense: 40
  price: 9500
  main_equipment_slots: 1
  utility_equipment_slots: 4
  align_time: 20
  target_time: 20
  crafting: {"asteroid.nickel_ore": 80, "asteroid.cobalt_ore": 150, "materials.ai_components": 500, "materials.antimatter": 300, "asteroid.titanium_ore": 150}
  crafting_duration: 1000
  type: "Freighter"
  

# Faction Ships

# Helix Collective

Leviathan:
  image: leviathan.png
  thruster-image: leviathan-thrusters.png
  storage: 150
  hp: 2500
  defense: 45
  price: 60000
  main_equipment_slots: 6
  utility_equipment_slots: 4
  align_time: 30
  target_time: 30
  crafting: {"materials.ai_components": 1000, "materials.metal_plates": 200, "asteroid.tryon_ore": 500}
  crafting_duration: 2000
  faction: 1
  reputation_requirement: 7
  type: "Combat"

Behemoth:
  image: behemoth.png
  thruster-image: behemoth-thrusters.png
  storage: 150
  hp: 1000
  defense: 45
  price: 45000
  main_equipment_slots: 4
  utility_equipment_slots: 3
  align_time: 20
  target_time: 20
  crafting: {"materials.ai_components": 500, "materials.metal_plates": 200, "asteroid.tryon_ore": 500}
  crafting_duration: 1500
  faction: 1
  reputation_requirement: 6
  type: "Combat"
  
Vanguard:
  image: vanguard.png
  thruster-image: vanguard-thrusters.png
  storage: 100
  hp: 800
  defense: 40
  price: 36000
  main_equipment_slots: 3
  utility_equipment_slots: 3
  align_time: 15
  target_time: 15
  crafting: {"materials.ai_components": 500, "materials.metal_plates": 450, "asteroid.titanium_ore": 500}
  crafting_duration: 1200
  faction: 1
  reputation_requirement: 5
  type: "Combat"

Intervention:
  image: intervention.png
  thruster-image: intervention-thrusters.png
  storage: 20
  hp: 400
  defense: 20
  price: 13500
  main_equipment_slots: 3
  utility_equipment_slots: 1
  align_time: 3
  target_time: 3
  crafting: {"materials.ai_components": 200, "materials.metal_plates": 100, "asteroid.titanium_ore": 100}
  crafting_duration: 500
  faction: 1
  reputation_requirement: 5
  type: "Hunter"
  
# Core Republic

Escorial:
  image: escorial.png
  thruster-image: escorial-thrusters.png
  storage: 500
  hp: 1000
  defense: 45
  price: 60000
  main_equipment_slots: 2
  utility_equipment_slots: 5
  align_time: 30
  target_time: 30
  crafting: {"materials.sensor_electronics": 900, "materials.fusion_electronics": 300, "asteroid.tryon_ore": 500}
  crafting_duration: 2000
  faction: 3
  reputation_requirement: 7
  type: "Freighter"
  
Aurora:
  image: aurora.png
  thruster-image: aurora-thrusters.png
  storage: 400
  hp: 850
  defense: 45
  price: 45000
  main_equipment_slots: 2
  utility_equipment_slots: 5
  align_time: 25
  target_time: 25
  crafting: {"materials.sensor_electronics": 500, "materials.fusion_electronics": 250, "asteroid.tryon_ore": 500}
  crafting_duration: 1500
  faction: 3
  reputation_requirement: 6
  type: "Freighter"

Aquila:
  image: aquila.png
  thruster-image: aquila-thrusters.png
  storage: 350
  hp: 850
  defense: 40
  price: 36000
  main_equipment_slots: 2
  utility_equipment_slots: 4
  align_time: 20
  target_time: 20
  crafting: {"materials.sensor_electronics": 500, "materials.fusion_electronics": 450, "asteroid.titanium_ore": 500}
  crafting_duration: 1200
  faction: 3
  reputation_requirement: 6
  type: "Freighter"

Lupus:
  image: lupus.png
  thruster-image: lupus-thrusters.png
  storage: 200
  hp: 400
  defense: 30
  price: 13500
  main_equipment_slots: 1
  utility_equipment_slots: 3
  align_time: 15
  target_time: 15
  crafting: {"materials.sensor_electronics": 200, "materials.fusion_electronics": 100, "asteroid.titanium_ore": 100}
  crafting_duration: 500
  faction: 3
  reputation_requirement: 5
  type: "Freighter"
  
# Caldarius Federation

Spectrum:
  image: spectrum.png
  thruster-image: spectrum-thrusters.png
  storage: 150
  hp: 2500
  defense: 55
  price: 60000
  main_equipment_slots: 4
  utility_equipment_slots: 6
  align_time: 25
  target_time: 25
  crafting: {"materials.laser_diodes": 1000, "materials.antimatter": 250, "asteroid.tryon_ore": 500}
  crafting_duration: 2000
  faction: 2
  reputation_requirement: 7
  type: "Multipurpose"

Yucatan:
  image: yucatan.png
  thruster-image: yucatan-thrusters.png
  storage: 150
  hp: 2000
  defense: 50
  price: 45000
  main_equipment_slots: 3
  utility_equipment_slots: 4
  align_time: 20
  target_time: 20
  crafting: {"materials.laser_diodes": 500, "materials.antimatter": 250, "asteroid.tryon_ore": 500}
  crafting_duration: 1500
  faction: 2
  reputation_requirement: 6
  type: "Multipurpose"
  
Cromwell:
  image: cromwell.png
  thruster-image: cromwell-thrusters.png
  storage: 100
  hp: 1500
  defense: 50
  price: 36000
  main_equipment_slots: 3
  utility_equipment_slots: 3
  align_time: 20
  target_time: 20
  crafting: {"materials.laser_diodes": 500, "materials.antimatter": 450, "asteroid.titanium_ore": 500}
  crafting_duration: 1200
  faction: 2
  reputation_requirement: 6
  type: "Multipurpose"
  
Analyzer:
  image: analyzer.png
  thruster-image: analyzer-thrusters.png
  storage: 20
  hp: 1000
  defense: 35
  price: 13500
  main_equipment_slots: 2
  utility_equipment_slots: 2
  align_time: 15
  target_time: 15
  crafting: {"materials.laser_diodes": 200, "materials.antimatter": 100, "asteroid.titanium_ore": 100}
  crafting_duration: 500
  faction: 2
  reputation_requirement: 5
  type: "Multipurpose"