version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - database
    ports:
      - "3000:3000"
    environment:
      - DATABASE_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stellar
      - REDIS_URL=redis://redis:6379/1
    volumes:
      - ".:/myapp"

  redis:
    image: redis:5.0.3-alpine

  sidekiq:
    depends_on:
      - database
      - redis
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: sidekiq
    volumes:
      - ".:/myapp"
    environment:
      - DATABASE_HOST=database
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stellar
      - REDIS_URL=redis://redis:6379/1

  database:
    image: postgres:11.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stellar

volumes:
  db_data:
