version: "3"

services:
  app:
    build:
      context: .      
      dockerfile: docker/Dockerfile
    image: venarius/stellar-app:latest
    depends_on:
      - database
    ports:
      - "443:443"

  redis:
    image: redis:5.0.3-alpine

  sidekiq:
    depends_on:
      - database
      - redis
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: venarius/stellar-app:latest
    command: rvm-exec 2.5.3 bundle exec sidekiq -C config/sidekiq.yml -e production

  database:
    image: postgres:11.2-alpine
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
